# Generated by Django 3.1.7 on 2021-03-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210319_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=30, verbose_name='Dirección'),
        ),
    ]
